### ISSUE TITLE
In Active branch : Samples,  getting installation error in gatekeeper

### ISSUE THREAD

**Issue by vallurivinod** [germinateplatform/germinate#21]
Installation is going fine with 3.4 version for both germinate and gk. In 3.4 germinate-importer.jar is missing. To get that plugin i used the latest code which is updated by u, though it is saying missing of classes while running the plugin.

BUILD FAILED
/var/lib/tomcat8/webapps/ROOT/gatekeeper/build.xml:102: java.io.IOException: Error writing request body to server
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3536)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3519)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.apache.catalina.ant.AbstractCatalinaTask.execute(AbstractCatalinaTask.java:242)
	at org.apache.catalina.ant.DeployTask.execute(DeployTask.java:194)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
	Suppressed: java.io.IOException: insufficient data written
		at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3558)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		at org.apache.catalina.ant.AbstractCatalinaTask.execute(AbstractCatalinaTask.java:245)

**Comment by sebastian-raubach** [comment]
Hello,
The stack trace indicates that the .war file couldn't be deployed to Tomcat.
In your question you are referring to missing classes when using the `germinate-importer.jar`, though?
Can you please clarify?

**Comment by vallurivinod** [comment]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/Options
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
root@vinod:/var/lib/tomcat8/webapps/ROOT/germinate/src# java -cp ../germinate-importer.jar jhi.germinate.util.importer.genotype.GenotypeDataImporter 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/Options
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by vallurivinod** [comment]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/Options
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by sebastian-raubach** [comment]
Make sure you run the `.jar` file from the root directory of the Germinate source code. The importer you should be using is `ExcelGenotypeDataImporter` not `GenotypeDataImporter`.

**Comment by vallurivinod** [comment]
i added below code to build.xml, 
<target name="build-importer-jar" depends="build-project">
		<jar destfile="germinate-importer.jar">
			<manifest>
				<attribute name="Main-Class" value="jhi.germinate.util.importer.reader.DataImporter"/>
				<attribute name="Class-Path" value="${manifest.classpath}"/>
			</manifest>
			<fileset dir="${build.dir}/WEB-INF/classes">
				<include name="**/germinate/util/**" />
				<exclude name="**/germinate/shared/search/**" />
				<include name="**/germinate/shared/**" />
				<exclude name="**/germinate/server/service/**" />
				<include name="**/germinate/server/**" />
			</fileset>
		</jar>

		<antcall target="delete_old_stuff"/>
	</target>

**Comment by vallurivinod** [comment]
i added this code to build.xml
<target name="build-importer-jar" depends="build-project">
		<jar destfile="germinate-importer.jar">
			<manifest>
				<attribute name="Main-Class" value="jhi.germinate.util.importer.reader.DataImporter"/>
				<attribute name="Class-Path" value="${manifest.classpath}"/>
			</manifest>
			<fileset dir="${build.dir}/WEB-INF/classes">
				<include name="**/germinate/util/**" />
				<exclude name="**/germinate/shared/search/**" />
				<include name="**/germinate/shared/**" />
				<exclude name="**/germinate/server/service/**" />
				<include name="**/germinate/server/**" />
			</fileset>
		</jar>

		<antcall target="delete_old_stuff"/>
	</target>

**Comment by vallurivinod** [comment]
``<target name="build-importer-jar" depends="build-project">
		<jar destfile="germinate-importer.jar">
			<manifest>
				<attribute name="Main-Class" value="jhi.germinate.util.importer.reader.DataImporter"/>
				<attribute name="Class-Path" value="${manifest.classpath}"/>
			</manifest>
			<fileset dir="${build.dir}/WEB-INF/classes">
				<include name="**/germinate/util/**" />
				<exclude name="**/germinate/shared/search/**" />
				<include name="**/germinate/shared/**" />
				<exclude name="**/germinate/server/service/**" />
				<include name="**/germinate/server/**" />
			</fileset>
		</jar>

		<antcall target="delete_old_stuff"/>
	</target>

**Comment by vallurivinod** [comment]
i runned it from the root directory of the Germinate source code. i cant find ExcelGenotypeDataImporter,
only  ExcelGenotypeDataReader i can found in util

**Comment by vallurivinod** [comment]
to which table i can  import snp data  using Daim

**Comment by vallurivinod** [comment]
how to generate germinate-importer.jar plugin in 3.4 version

**Comment by sebastian-raubach** [comment]
You can import the germplasm into `germinatebase`, the markers into `markers`, `markertypes`, `maps`, `mapdefinitions`, `mapfeaturetypes`.
The actual SNP calls go into a `.hdf5` file that can be generated using `FJTabbedToHdf5Converter` from the Flapjack `.jar` file. That file then needs to be placed in either the external data folder or `instance-stuff/<your-instance>/data/genotype` and it's filename goes into the `source_file` field in the `datasets` table.
OR just wait for 3.5.0.

You can't create the `.jar` file in version 3.4.0. It didn't exist back then.

Please don't create multiple at the same time, combine everything you want to say in a single post and then wait for feedback. It's becoming very cluttered in here.

**Comment by vallurivinod** [comment]
what is the format required and whether to remove any columns in snp file .
i converted my vcf file to text file. or i should follow same format of allele template

**Comment by sebastian-raubach** [comment]
The text file that goes into `FJTabbedToHdf5Converter` needs to be in the same format as the `DATA` tab in the template, i.e. germplasm/lines along the side, markers along the top, tab delimited SNP calls in the cells.

**Comment by sebastian-raubach** [comment]
Correction: The same format as the `DATA` tab starting from row 3 (not including the map information).

**Comment by vallurivinod** [comment]
Got a error while running 
java -jar flapjack.jar FJTabbedToHdf5Converter snp_test.txt snp.h5
Flapjack x.xx.xx.xx on Linux (amd64)
DPI: 96, scaling: 1.0, auto=true
Exception in thread "main" java.lang.NoClassDefFoundError: org/jfree/data/xy/XYDataset
	at jhi.flapjack.gui.visualization.ChromosomePanel.<init>(ChromosomePanel.java:32)
	at jhi.flapjack.gui.NavPanel.<init>(NavPanel.java:68)
	at jhi.flapjack.gui.WinMain.<init>(WinMain.java:54)
	at jhi.flapjack.gui.Flapjack.<init>(Flapjack.java:115)
	at jhi.flapjack.gui.Flapjack.main(Flapjack.java:65)
Caused by: java.lang.ClassNotFoundException: org.jfree.data.xy.XYDataset
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

**Comment by sebastian-raubach** [comment]
Try:

    java -cp flapjack.jar jhi.flapjack.io.cmd.FJTabbedToHdf5Converter --genotypes=snp_text.txt --hdf5=snp.h5

**Comment by vallurivinod** [comment]
Hi sebastian,
In marker details, marker dataset is not visible. i created dataset also. how i want to add markers to that data set
![germinate](https://user-images.githubusercontent.com/38492349/39113724-3724a95c-46fa-11e8-92df-1d45ebc8a7ed.jpeg)

**Comment by sebastian-raubach** [comment]
It'll show up there if the marker is in the dataset you created.
However, I had a look at the code and at your previous comments and the hdf5 file needs to have a `.hdf5` extension, not `.h5`.

**Comment by vallurivinod** [comment]
i given hdf5 as extension

**Comment by sebastian-raubach** [comment]
You can try using [HDFView](https://support.hdfgroup.org/products/java/hdfview/) to open your file and check if `marker1` is under the markers list.
You should also check if your hdf5 file was properly deployed by checking the `data` directory of your web app.

**Comment by vallurivinod** [comment]
Now it is working, case sensitive error

**Comment by vallurivinod** [comment]
Apr 23, 2018 2:29:32 PM jhi.germinate.shared.exception.BaseException logException
SEVERE: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'datasets.license_id' in 'on clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'datasets.license_id' in 'on clause'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.Util.getInstance(Util.java:372)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
        at jhi.germinate.server.database.DatabaseStatement.query(DatabaseStatement.java:245)
        at jhi.germinate.server.database.query.DatabaseObjectQuery$ExecutedDatabaseObjectQuery.<init>(DatabaseObjectQuery.java:87)
        at jhi.germinate.server.database.query.DatabaseObjectQuery.run(DatabaseObjectQuery.java:51)
        at jhi.germinate.server.manager.DatasetManager.getAllForFilter(DatasetManager.java:175)
        at jhi.germinate.server.service.DatasetServiceImpl.getForFilter(DatasetServiceImpl.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at jhi.germinate.server.util.BaseRemoteServiceServlet.processCall(BaseRemoteServiceServlet.java:49)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at jhi.germinate.server.util.GWTCacheControlFilter.doFilter(GWTCacheControlFilter.java:63)

**Comment by sebastian-raubach** [comment]
What version are you using? It looks like a database column is missing, but that'd be included in 3.4.0

**Comment by vallurivinod** [comment]
Hi sebastian.
 when downloading  the dataset from genotypes, downloaded file contains only some data while compared to the hdf5. can i know what is the issue. hdf5 is of 1.5 gb, downloaded file is of 351mb

**Comment by sebastian-raubach** [comment]
Did you select all the accessions and all the markers that are in the file? Did you also make sure that the markers are on the map that you selected?
Also, which format did you download? The .txt file or the .flapjack file?
Would you be able to share them with us via germinate@hutton.ac.uk?

**Comment by vallurivinod** [comment]
txt format

**Comment by vallurivinod** [comment]
i downloaded from Experiment details page which contains download option

**Comment by sebastian-raubach** [comment]
That button just takes everything that's in the hdf5 file and writes it to a txt file.
Without looking at both the hdf5 and the output file, I'm not sure how I can help you.

**Comment by vallurivinod** [comment]
is high memory required  to right output file?

**Comment by sebastian-raubach** [comment]
No, but be sure to check the log files in `<Tomcat folder>/logs/<Name of Germinate instance>-<date>.log`

**Comment by vallurivinod** [comment]
it is not showing any error in the logs.
while downloading it is appeared in the following way in the logs:
Hdf5 file opened for reading: 1 (ms)
Read and filtered lines: 4032 (ms)
Read and filtered markers: 33 (ms)
Read and mapped markers: 16 (ms)
Read statetable: 5 (ms)

**Comment by sebastian-raubach** [comment]
Do those numbers match to with the numbers is markers and lines on your file?

**Comment by vallurivinod** [comment]
no

**Comment by sebastian-raubach** [comment]
Without seeing the file, there isn't much we can do now.
