### ISSUE TITLE
Regarding foreign_id field in dataset members table and how to enable to show accessions are present in particular dataset.

### ISSUE THREAD

**Issue by lenora09** [germinateplatform/germinate#22]
I want to know information about foreign_id field in datasetmemebers table. And how to show  accessions belongs to particular dataset in the passport data details page as      
Shown in Ur demo version

**Comment by sebastian-raubach** [comment]
`foreign_id` needs to map to `germinatebase.id` and the `datasetmembertype_id` needs to be set to the corresponding type.

**Comment by lenora09** [comment]
There will be so many germinate base id's based on accessions, then how to map in foreign_id

**Comment by lenora09** [comment]
Is any availability of latest docker image of germinate 3.5

**Comment by sebastian-raubach** [comment]
You'll need one entry in that table per member, i.e. accession.

**Comment by sebastian-raubach** [comment]
If you use the Excel data importer code (see wiki), those entries will be created automatically.

**Comment by lenora09** [comment]
K I will try and will get back to u if problem arises

**Comment by lenora09** [comment]
i got a problem when downloading genotype flapjack file. plz help me to solve this issue.
Firefox can’t find the file at http://localhost:8080/test/germinate/file?sid=37bc1b76-5b26-498e-a02f-bf2c1206d160&file-locale=en_GB&file-location=temporary&file-path=genotype_207f02c5-54f2-4166-8a7b-660772883636.flapjack

**Comment by lenora09** [comment]
log file:
Hdf5 file opened for reading: 12 (ms)

Read and filtered lines: 12 (ms)

Read and filtered markers: 3946 (ms)

Read and mapped markers: 24 (ms)
Read statetable: 5 (ms)
Output lines to genotype file: 13027 (ms)

HDF5 file converted to Flapjack genotype format
jhi.germinate.shared.exception.DatabaseException: Unable to connect to the database: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at jhi.germinate.server.database.Database.connect(Database.java:171)
        at jhi.germinate.server.database.Database.connect(Database.java:281)
        at jhi.germinate.server.database.query.GerminateQuery.init(GerminateQuery.java:82)
        at jhi.germinate.server.database.query.ValueQuery.execute(ValueQuery.java:88)
        at jhi.germinate.server.database.query.ValueQuery.execute(ValueQuery.java:76)
        at jhi.germinate.server.database.DatasetMetaJob.run(DatasetMetaJob.java:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sebastian-raubach** [comment]
The file seems to have been created successfully. The error message you see is unrelated to the HDF5 code, but still indicates that Germinate cannot talk to your database. The connection timed out.

**Comment by lenora09** [comment]
genotype and map are generating in the temp folder but after click on flapjack file generation shows wait progress bar and after shows above error

**Comment by sebastian-raubach** [comment]
What error does it show on the client?

**Comment by lenora09** [comment]
Firefox can’t find the file at http://localhost:8080/test/germinate/file?sid=37bc1b76-5b26-498e-a02f-bf2c1206d160&file-locale=en_GB&file-location=temporary&file-path=genotype_207f02c5-54f2-4166-8a7b-660772883636.flapjack

**Comment by sebastian-raubach** [comment]
Would you be able to send the genotype and map file to germinate@hutton.ac.uk ?

**Comment by lenora09** [comment]
During tomcat startup it is showing a exception in log
INFO: Server startup in 86156 ms
jhi.germinate.shared.exception.DatabaseException
        at jhi.germinate.server.database.DatabaseResult.getDate(DatabaseResult.java:287)
        at jhi.germinate.shared.datastructure.database.Accession$Parser.parse(Accession.java:555)
        at jhi.germinate.shared.datastructure.database.Accession$PDCIParser.parse(Accession.java:610)
        at jhi.germinate.shared.datastructure.database.Accession$PDCIParser.parse(Accession.java:604)
        at jhi.germinate.server.database.query.DatabaseObjectStreamer.next(DatabaseObjectStreamer.java:70)
        at jhi.germinate.server.database.PDCIRunnable.run(PDCIRunnable.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by lenora09** [comment]
In 3.4  every thing is working fine. i am getting problem in 3.5 version

**Comment by sebastian-raubach** [comment]
Try setting `Germinate.PDCI.Enabled` to `false` in your `config.properties`.

**Comment by lenora09** [comment]
i have more than 2 million markers. they are taking more time to load , what should i do to make them load faster. should i increase the java memory?

**Comment by lenora09** [comment]
i didnot have issue wih uploading, i have issue while clicking on the maps which contains markers.
maps with few markers are loading fast. if large amount of markers are present then taking time.

**Comment by sebastian-raubach** [comment]
The markers on the map are sorted by chromosome and position. Sorting 2 million markers takes some time.

**Comment by sebastian-raubach** [comment]
Closing this due to inactivity.
